{% set name = "ipynb-py-convert" %}
{% set version = "0.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 06c09644f85949939fa749a00fb7f398a0bfcad0e34320ca6666e0cb44b7ea74

build:
  noarch: python
  number: 0
  entry_points:
    - ipynb-py-convert = ipynb_py_convert.__main__:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - ipynb_py_convert

about:
  home: https://github.com/kiwi0fruit/ipynb-py-convert
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Convert .py files runnable in VSCode/Python or Atom/Hydrogen to jupyter .ipynb notebooks and vice versa
  doc_url: https://github.com/kiwi0fruit/ipynb-py-convert
  dev_url: https://github.com/kiwi0fruit/ipynb-py-convert

extra:
  recipe-maintainers:
    - kiwi0fruit
