travis:
  secure:
    BINSTAR_TOKEN: JEVq4bejiJpi8ZzeJwhk5whq6Pt8sYUM1oDYjOqsiuln90WGmhowIYjtW3sUaTR105n7Ry1hBLxMI7Y2HxNXMRUy3FQKQZaSO6WM7w8E5zaR8H/2rCJ5x0FKxsaP8pTJS91ca0TUMVKeLn0KZBst4pszE/I6J6jRPl24t7Q5tKOtiBl8E1Xz1twUrICs6MKQtFPC3S0UJxteO360xEplXKDBokCOsk1uGmIm5Pi9wIi0tA5C5kIfXtfLohUmL4wozvm3Qz0H51v5ci8mqr25qqNFOI1r5PikqTVWlra5v39bilV7RJ+S6wzvUiHZY2tQRu0GG54ZbPUXllit2Y+8aX5NLF4KKZb1dQnDIK1O0EMc54YsA0+NzO27FIunBR1tkcfEe/AZe3kCpMQwrHIJSgYE4XhaM4fwMENq3MyFrLTHrsW58AYQD15wW+dW/dLfV2PWHVvEHw0Owb8LX6bhlLKL3Y2w1plQgzvAE5cQ5FtMtPXOxwmh5FMSzPJOcrJn+4FEUaRjLeMyq67UAdJJ+sjNlaalw+Fk38BW+uh0zWJ2W8aooSOh6y85+VRbrDbJR6YpaAyTqlA7KKbHAxdSZgCgul1DFJWMYYdUOob4hhtmvG79GnwADRq1Flf6n/obRP4q+EYnd2OoGRPOFe/hJqqWswvIDGDSgRKb65Tnjgo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
