travis:
  secure:
    BINSTAR_TOKEN: Q4I/hgaLDm52MZC2a5qmooQRvbZH2xIuwxpG7yqjdxEEPJHvQg4edk/zNXnCNEDTsOK3bUKaCjq62qVKGSpv9aQ3rHaenaOyrOzOebYla+s6/vn6pqVwvF7Nx5/rgEWLnD7q17PB3Vxs6Ku3WfJLXsPiP9CRN0IwSmR5CNpcZ+dqD/J0CDBIJCY3yMTuPF35qfm4alvZlZ6/JvsPffcL45fl54Uc6/XUzqRDkOKuOySJgYSatwVhrOVpXj7H8zNc9WJrN70DHUiZaz8pZZ+OhyFLXFQIl8zp2q/ZQOawQfvpZReNaRA4pQHscswHculSyrBacGsuTG8ZAzdS63xEyY0wCi5/WsnKypn5+xPcit0+rT5VJwomieJjUG9ttvmXAgXu7B2xvF+O3ty0xxMLd4KabaTkJzXXsxFdJZLXJLNvBQC5rMBjuwrlDezy1enws86rbrWadFWl8cTxUFV0ycc9mHmb3730iqHYS4y71wFdes+ncAblufHIH+1mMMwc6JrxrBpvbtN4VWZqQQLJ0k7vD+QiSo/wz2M34+/U/kb/tLnTlRq42yKAVUCWziGVHI5QfeTIkteNahfxix+9TMOUDt7eVJvc1nH19S1wPO4My+kuhoRad6PEd65ePHcCk/HNonTEEOrIAa+PqJZ4jR83NXuT9vrqZ81t73w17AE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
